2021-01-22 16:44:10,342 ERROR [scheduling-1] (ScheduleProductTask:139) 更新产品任务失败：
### Error querying database.  Cause: com.mysql.cj.jdbc.exceptions.CommunicationsException: The last packet successfully received from the server was 55,798 milliseconds ago.  The last packet sent successfully to the server was 55,802 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.
### The error may exist in file [G:\diskJ\javaProject\business\target\classes\mapper\WorkFlowOrderDao.xml]
### The error may involve com.business.dao.WorkFlowOrderDao.selectProductList-Inline
### The error occurred while setting parameters
### SQL: select orderType,taskSerialNumber,taskPriority,taskStatus,taskMode,jobTaskID,satelliteName,dataSelectType,productLevel,out_productdir,orderStatus,startTime,endTime,logName,logPath,resampleKernal,fileResource from workflow_order where orderStatus = ? and taskMode='PRTask'
### Cause: com.mysql.cj.jdbc.exceptions.CommunicationsException: The last packet successfully received from the server was 55,798 milliseconds ago.  The last packet sent successfully to the server was 55,802 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.
; The last packet successfully received from the server was 55,798 milliseconds ago.  The last packet sent successfully to the server was 55,802 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.; nested exception is com.mysql.cj.jdbc.exceptions.CommunicationsException: The last packet successfully received from the server was 55,798 milliseconds ago.  The last packet sent successfully to the server was 55,802 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.
